### PR TITLE
Add complete refund notify and adjust composer.json file.

### PR DESCRIPTION
**Pull request by maxsky**

### CODE REVIEW

**Comment by gdcfivepercent** [comment]
Great!

**Comment by maxsky** [comment]
@gdcfivepercent Waiting for author merge it.

**Comment by gdcfivepercent** [comment]
这是全额退款接口吗

**Comment by maxsky** [comment]
@gdcfivepercent 根据 `trade_status` 判断，全额为 `TRADE_CLOSED`，部分为 `TRADE_SUCCESS`

**Pull request merged**
